# python -m train --config-name=c4_a100x8x4_1b +paths.model_name=1b
defaults:
- c4_a100x8_base
- _self_

num_hosts: 4

mesh:
  d: 16
  t: 1

training:
  warmup_steps: 800
  steps:        8000 
  steps_for_lr: 8000 
  learning_rate: 5.0e-4
  tokens:
    batch: 256

model:
  d_model: 256 
  n_q_per_kv: 1
  n_kv: 16 
  d_head: 8 
  layers: 8
  d_ff: 1024 
  vocab: 32768
  rope_max_timescale: 10000
  
checkpoint_interval: 2500