# python -m train --config-name=c4_a100x8x4_37m +paths.model_name=270m
defaults:
- c4_a100x8_base
- _self_

num_hosts: 4

mesh:
  d: 16
  t: 1

training:
  warmup_steps: 290 
  steps:        2900 
  steps_for_lr: 2900 
  learning_rate: 7.3e-3
  tokens:
    batch: 256
  use_grad_clip: False

model:
  d_model: 256 
  n_q_per_kv: 1
  n_kv: 8 
  d_head: 128 
  layers: 8
  d_ff: 2048 
  vocab: 32768
  rope_max_timescale: 10000
  a_attn: 1.
  a_output: 1.
  base:
    d_model: 256 
    n_q_per_kv: 1
    n_kv: 8 
    d_head: 128 
    layers: 8
    d_ff: 2048

checkpoint_interval: 9200
