# python -m train --config-name=c4_a100x8_270m +paths.model_name=270m
defaults:
- c4_a100x8_base
- _self_

num_hosts: 4

mesh:
  d: 16 
  t: 1

training:
  warmup_steps: 2300
  steps:        23000
  steps_for_lr: 23000
  learning_rate: 8.0e-4
  tokens:
    batch: 256
  use_grad_clip: true

model:
  d_model: 1024
  n_q_per_kv: 1
  n_kv: 16
  d_head: 128
  layers: 8
  d_ff: 8192
  vocab: 32768
  rope_max_timescale: 10000
  a_attn: 1.
  a_output: 1.
  zero_queries: true
  zero_unembed: true
  base:
    d_model: 1024
    n_q_per_kv: 1
    n_kv: 16
    d_head: 128
    d_ff: 8192
  parameterization: "sp"
  fully_aligned: false
  gamma_embed: 1.
  gamma_hidden: 1. 
  gamma_unembed: 1.
   
checkpoint_interval: 9200
