# python -m train --config-name=c4_a100x8x4_37m +paths.model_name=37m
defaults:
- c4_a100x8_base
- _self_

num_hosts: 4

mesh:
  d: 16
  t: 1

training:
  warmup_steps: 290 
  steps:        2900 
  steps_for_lr: 2900 
  learning_rate: 7.3e-3
  tokens:
    batch: 256
  use_grad_clip: true

model:
  d_model: 256 
  n_q_per_kv: 1
  n_kv: 16 
  d_head: 64 
  layers: 8
  d_ff: 2048 
  vocab: 32768
  rope_max_timescale: 10000
  a_attn: 1.
  a_output: 1.
  zero_queries: true
  zero_unembed: true
  base:
    d_model: 256 
    n_q_per_kv: 1
    n_kv: 16 
    d_head: 64
    d_ff: 2048
  parameterization: "sp" 
  fully_aligned: false
  gamma_embed: 6.2539770944178406
  gamma_hidden: 1.4848467942851378 
  gamma_unembed: 1.4897826620883678

checkpoint_interval: 9200
