# python -m train --config-name=c4_a100x8x4_10m +paths.model_name=270m
defaults:
- c4_a100x8_base
- _self_

num_hosts: 1

mesh:
  d: 1 
  t: 1

training:
  warmup_steps: 110
  steps:        1100
  steps_for_lr: 1100
  learning_rate: 3.0e-2
  tokens:
    len: 512 
    batch: 64 
  use_grad_clip: true

model:
  d_model: 128
  n_q_per_kv: 1
  n_kv: 16 
  d_head: 32 
  d_ff: 512 
  layers: 8
  vocab: 32768

  rope_max_timescale: 10000
  cope_n_pos_max: 64
  apply_cope: true
  apply_rope: true

  base:
    d_model: 128
    n_q_per_kv: 1
    n_kv: 16 
    d_head: 32 
    d_ff: 512 
  
  a_attn: 1.
  a_output: 1.
  zero_queries: true
  zero_unembed: true

  parameterization: "sp" 
  fully_aligned: false
  gamma_embed: 1. 
  gamma_hidden: 1. 
  gamma_unembed: 1. 


  
checkpoint_interval: 9200
