defaults:
  - _self_

num_hosts: 4

mesh:
  d: 16
  t: 1

training:
  tokens:
    length: 2048
    batch: 256
  
  # AdamW optimizer parameters
  # We use AdamW following Llama2's training details, see https://arxiv.org/pdf/2307.09288.pdf section 2.2
  adam_b1: 0.95 # Exponential decay rate to track the first moment of past gradients.
  adam_b2: 0.95 # Exponential decay rate to track the second moment of past gradients.
  adam_eps: 1.e-8 # A small constant applied to denominator outside of the square root.
  adam_eps_root: 0. # A small constant applied to denominator inside the square root.
  weight_decay: 0.1 # AdamW Weight decay

  # We take inspiration from Llama2's learning rate (LR) schedule, see https://arxiv.org/pdf/2307.09288.pdf section 2.2
  # Learning rate schedule has two parts:
  # 1) Linear warmup from 0 to [learning_rate] over steps 0 to [learning_rate_schedule_steps * warmup_steps_fraction]
  # 2) Cosine decay from [learning_rate] to [learning_rate * cosine_learning_rate_final_fraction] from warmup to learning_rate_schedule_steps
  
  cosine_learning_rate_final_fraction: 0.1
  use_grad_clip: true
  use_gpu: false
  use_single_pod: false

model:
  vocab: 32768
  rope_max_timescale: 10000

hf_dataset:
  name: default
  num_workers: 1
  tokenizer: mistralai/Mistral-7B-v0.1 # may require huggingface-cli login
  sequences_packed_per_batch: 120
  seed: 0
  max_retries: 5

paths:
  # root_working_dir can also be a path on a local filesystem
  root_working_dir: "/tmp/"

io:
  max_io_threads: 1024

checkpoint_interval: 9200 