# Command to run on your CPU:
#   XLA_FLAGS=--xla_force_host_platform_device_count=8 python -m train --config-name=local_test_synthetic +paths.model_name=synthetic_000

defaults:
- base
- _self_

training:
  warmup_steps: 10
  steps:        50
  steps_for_lr: 100
  tokens:
    batch: 64
    len: 64

model:
  d_model: 256
  n_q_per_kv: 2
  n_kv: 2
  d_head: 32
  layers: 2
  vocab: 32768 
  d_ff: 1024
  rope_max_timescale: 256
  a_attn: 1
  a_output: 1

  base:
    d_model: 256
    n_q_per_kv: 2
    n_kv: 2
    d_head: 32
    layers: 2
    d_ff: 1024

paths:
  root_working_dir: '/tmp'

checkpoint_interval: 10
num_hosts: 1

mesh:
  d: 4
  t: 2

flat_tokens:
  filespec: 'gcs://flat_tokens/20b'   # Fill in
  streams: 1
  read_blocks_per_shuffle_buffer: 128
  sequences_per_read_block: 1024
  seed: 0
  sequence_packing: true
