# python -m train --config-name=c4_a100x8x4_37m +paths.model_name=270m
defaults:
  - slim_base
  - _self_

training:
  warmup_steps: 300
  steps: 3000
  steps_for_lr: 3000
  learning_rate: 1.0.e-3

model:
  d_model: 512
  n_q_per_kv: 1
  n_kv: 8
  d_head: 128
  d_ff: 2048
  layers: 8
  
  base:
    d_model: 256
    n_q_per_kv: 1
    n_kv: 16
    d_head: 64
    d_ff: 1024

  a_attn: 1.
  a_output: 1.
  zero_queries: true
  zero_unembed: true

  parameterization: "sp"
  fully_aligned: false
  gamma_embed: 1.
  gamma_hidden: 1.
  gamma_unembed: 1.

