# python -m train --config-name=c4_a100x8x4_10m +paths.model_name=270m
defaults:
- slim_base
- _self_

model:
  d_model: 128
  n_q_per_kv: 1
  n_kv: 8
  d_head: 32
  d_ff: 512
  layers: 4
  
  base:
    d_model: 64
    n_q_per_kv: 1
    n_kv: 16
    d_head: 16
    d_ff: 256

  a_attn: 1.
  a_output: 1.
  zero_queries: true
  zero_unembed: true

  parameterization: "sp"
  fully_aligned: false
  gamma_embed: 1.
  gamma_hidden: 1.
  gamma_unembed: 1.
  
checkpoint_interval: 9200

hf_dataset:
  num_workers: 0 