# python -m train --config-name=c4_a100x8x4_10m +paths.model_name=270m
defaults:
- synthetic_base
- _self_

num_hosts: 1

mesh:
  d: 1 
  t: 1

training:
  warmup_steps: 900
  steps:        9000
  steps_for_lr: 9000
  learning_rate: 3.0e-3 
  tokens:
    batch: 64 
    len: 512
  use_grad_clip: true
  use_gpu: true

model:
  d_model: 256
  n_q_per_kv: 1
  n_kv: 16 
  d_head: 64 
  layers: 8
  d_ff: 1024 
  vocab: 49 
  rope_max_timescale: 10000
  a_attn: 1.
  a_output: 1.
  zero_queries: true
  zero_unembed: true
  base:
    d_model: 256 
    n_q_per_kv: 1
    n_kv: 16 
    d_head: 64 
    d_ff: 1024 
  parameterization: "sp" 
  fully_aligned: false
  gamma_embed: 1. 
  gamma_hidden: 1. 
  gamma_unembed: 1.
  
checkpoint_interval: 9200

paths:
  root_working_dir: "/media/clankur/HDD/models"

